from pyspark.sql.types import (
    StructType, 
    StructField, 
    StringType,
    LongType,
    DoubleType)



def overview_schema(): 
    return StructType([
    StructField("Symbol", StringType(), True),
    StructField("AssetType", StringType(), True),
    StructField("Name", StringType(), True),
    StructField("Description", StringType(), True),
    StructField("CIK", StringType(), True),
    StructField("Exchange", StringType(), True),
    StructField("Currency", StringType(), True),
    StructField("Country", StringType(), True),
    StructField("Sector", StringType(), True),
    StructField("Industry", StringType(), True),
    StructField("Address", StringType(), True),
    StructField("FiscalYearEnd", StringType(), True),
    StructField("LatestQuarter", StringType(), True),
    StructField("MarketCapitalization", StringType(), True),
    StructField("EBITDA", StringType(), True),
    StructField("PERatio", StringType(), True),
    StructField("PEGRatio", StringType(), True),
    StructField("BookValue", StringType(), True),
    StructField("DividendPerShare", StringType(), True),
    StructField("DividendYield", StringType(), True),
    StructField("EPS", StringType(), True),
    StructField("RevenuePerShareTTM", StringType(), True),
    StructField("ProfitMargin", StringType(), True),
    StructField("OperatingMarginTTM", StringType(), True),
    StructField("ReturnOnAssetsTTM", StringType(), True),
    StructField("ReturnOnEquityTTM", StringType(), True),
    StructField("RevenueTTM", StringType(), True),
    StructField("GrossProfitTTM", StringType(), True),
    StructField("DilutedEPSTTM", StringType(), True),
    StructField("QuarterlyEarningsGrowthYOY", StringType(), True),
    StructField("QuarterlyRevenueGrowthYOY", StringType(), True),
    StructField("AnalystTargetPrice", StringType(), True),
    StructField("AnalystRatingStrongBuy", StringType(), True),
    StructField("AnalystRatingBuy", StringType(), True),
    StructField("AnalystRatingHold", StringType(), True),
    StructField("AnalystRatingSell", StringType(), True),
    StructField("AnalystRatingStrongSell", StringType(), True),
    StructField("TrailingPE", StringType(), True),
    StructField("ForwardPE", StringType(), True),
    StructField("PriceToSalesRatioTTM", StringType(), True),
    StructField("PriceToBookRatio", StringType(), True),
    StructField("EVToRevenue", StringType(), True),
    StructField("EVToEBITDA", StringType(), True),
    StructField("Beta", StringType(), True),
    StructField("52WeekHigh", StringType(), True),
    StructField("52WeekLow", StringType(), True),
    StructField("50DayMovingAverage", StringType(), True),
    StructField("200DayMovingAverage", StringType(), True),
    StructField("SharesOutstanding", StringType(), True),
    StructField("DividendDate", StringType(), True),
    StructField("ExDividendDate", StringType(), True)
])





'''


def overview_schema(): 
    return StructType([
    StructField("Symbol", StringType(), True),
    StructField("AssetType", StringType(), True),
    StructField("Name", StringType(), True),
    StructField("Description", StringType(), True),
    StructField("CIK", StringType(), True),
    StructField("Exchange", StringType(), True),
    StructField("Currency", StringType(), True),
    StructField("Country", StringType(), True),
    StructField("Sector", StringType(), True),
    StructField("Industry", StringType(), True),
    StructField("Address", StringType(), True),
    StructField("FiscalYearEnd", StringType(), True),
    StructField("LatestQuarter", StringType(), True),
    StructField("MarketCapitalization", LongType(), True),
    StructField("EBITDA", LongType(), True),
    StructField("PERatio", DoubleType(), True),
    StructField("PEGRatio", DoubleType(), True),
    StructField("BookValue", DoubleType(), True),
    StructField("DividendPerShare", DoubleType(), True),
    StructField("DividendYield", DoubleType(), True),
    StructField("EPS", DoubleType(), True),
    StructField("RevenuePerShareTTM", DoubleType(), True),
    StructField("ProfitMargin", DoubleType(), True),
    StructField("OperatingMarginTTM", DoubleType(), True),
    StructField("ReturnOnAssetsTTM", DoubleType(), True),
    StructField("ReturnOnEquityTTM", DoubleType(), True),
    StructField("RevenueTTM", LongType(), True),
    StructField("GrossProfitTTM", LongType(), True),
    StructField("DilutedEPSTTM", DoubleType(), True),
    StructField("QuarterlyEarningsGrowthYOY", DoubleType(), True),
    StructField("QuarterlyRevenueGrowthYOY", DoubleType(), True),
    StructField("AnalystTargetPrice", DoubleType(), True),
    StructField("AnalystRatingStrongBuy", LongType(), True),
    StructField("AnalystRatingBuy", LongType(), True),
    StructField("AnalystRatingHold", LongType(), True),
    StructField("AnalystRatingSell", LongType(), True),
    StructField("AnalystRatingStrongSell", LongType(), True),
    StructField("TrailingPE", DoubleType(), True),
    StructField("ForwardPE", DoubleType(), True),
    StructField("PriceToSalesRatioTTM", DoubleType(), True),
    StructField("PriceToBookRatio", DoubleType(), True),
    StructField("EVToRevenue", DoubleType(), True),
    StructField("EVToEBITDA", DoubleType(), True),
    StructField("Beta", DoubleType(), True),
    StructField("52WeekHigh", DoubleType(), True),
    StructField("52WeekLow", DoubleType(), True),
    StructField("50DayMovingAverage", DoubleType(), True),
    StructField("200DayMovingAverage", DoubleType(), True),
    StructField("SharesOutstanding", LongType(), True),
    StructField("DividendDate", StringType(), True),
    StructField("ExDividendDate", StringType(), True)
])

'''